### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#10]
write a Bubble Sort Algorithm.

**Comment by Brijeshthummar02** [comment]
hi there, @Saloni6111 i would work on this.

**Comment by Saloni6111** [comment]
> hi there, @Saloni6111 i would work on this.

@Brijeshthummar02 Sure, it's already assigned to you. Please go ahead!

**Comment by Anujmishra2005** [comment]
Hi @Saloni6111 , Please assign assign me this issue

**Comment by Saloni6111** [comment]
merged!
