### ISSUE TITLE
Making A Large Island

### ISSUE THREAD

**Issue by Amber-Mishra-2003** [Saloni6111/DSA_Problems-Hacktoberfest-2024#101]
Problem Statement :- You are given an n x n binary matrix grid. You are allowed to change at most one 0 to be 1.

Return the size of the largest island in grid after applying this operation.

An island is a 4-directionally connected group of 1s.

Input: grid = [[1,0],[0,1]]
Output: 3

Input: grid = [[1,1],[1,0]]
Output: 4

**Comment by Amber-Mishra-2003** [comment]
Kindly please assign me this issue

**Comment by Saloni6111** [comment]
> Kindly please assign me this issue

@Amber-Mishra-2003 Done!

**Comment by hemanthhhhhh** [comment]
Kindly assign me the issue

**Comment by Utkarsh-Aggarwal** [comment]
please assign this to  me my gfg profile https://www.geeksforgeeks.org/user/utkarshagbfsx/ @Saloni6111
