### ISSUE TITLE
Cherry Pickup

### ISSUE THREAD

**Issue by Amber-Mishra-2003** [Saloni6111/DSA_Problems-Hacktoberfest-2024#102]
Problem Statement :- You are given an n x n grid representing a field of cherries, each cell is one of three possible integers.

 -> 0 means the cell is empty, so you can pass through,
 -> 1 means the cell contains a cherry that you can pick up and pass through, or
 -> -1 means the cell contains a thorn that blocks your way.

Return the maximum number of cherries you can collect by following the rules below:

 -> Starting at the position (0, 0) and reaching (n - 1, n - 1) by moving right or down through valid path cells (cells with value 0 or 1).
 -> After reaching (n - 1, n - 1), returning to (0, 0) by moving left or up through valid path cells.
 -> When passing through a path cell containing a cherry, you pick it up, and the cell becomes an empty cell 0.
 -> If there is no valid path between (0, 0) and (n - 1, n - 1), then no cherries can be collected.

Input: grid = [[0,1,-1],[1,0,-1],[1,1,1]]
Output: 5

Input: grid = [[1,1,-1],[1,-1,1],[-1,1,1]]
Output: 0

**Comment by Amber-Mishra-2003** [comment]
Kindly please assign me this issue

**Comment by Saloni6111** [comment]
> Kindly please assign me this issue

@Amber-Mishra-2003 Done!

**Comment by hemanthhhhhh** [comment]
The Cherry Pickup problem is a dynamic programming problem on a 2D grid that challenges you to collect the maximum number of "cherries" while following a set of rules.
Please assign me the issue

**Comment by Utkarsh-Aggarwal** [comment]
hi i am a second year student , paving my way into open source can please assign this issue to me @Saloni6111

**Comment by Visha17** [comment]
Kindly please assign me this issue @Saloni6111 .I'll try?
