### ISSUE TITLE
Heuristic Search Algorithm or A* Algorithm

### ISSUE THREAD

**Issue by pankaj-bind** [Saloni6111/DSA_Problems-Hacktoberfest-2024#114]
Heuristic Search Algorithms are techniques used in search problems to find solutions more efficiently by using additional information, called a heuristic, to guide the search process. The goal is to prioritize paths that are more likely to lead to a solution, reducing the need to explore less promising paths.

Please assign me this issue

**Comment by Saloni6111** [comment]
> Heuristic Search Algorithms are techniques used in search problems to find solutions more efficiently by using additional information, called a heuristic, to guide the search process. The goal is to prioritize paths that are more likely to lead to a solution, reducing the need to explore less promising paths.
> 
> Please assign me this issue

@pankaj-bind it's already assigned to you. Please go ahead!

**Comment by dauntless05** [comment]
hi can please assign it to me !!
thanks
