### ISSUE TITLE
Knuth-Morris-Pratt (KMP) Algorithm

### ISSUE THREAD

**Issue by pankaj-bind** [Saloni6111/DSA_Problems-Hacktoberfest-2024#115]
The Knuth-Morris-Pratt (KMP) Algorithm is an efficient string-matching algorithm used to find occurrences of a "pattern" string within a "text" string. It improves upon the brute-force approach by avoiding unnecessary comparisons through preprocessing the pattern.

Assign me this issue.

**Comment by Saloni6111** [comment]
> The Knuth-Morris-Pratt (KMP) Algorithm is an efficient string-matching algorithm used to find occurrences of a "pattern" string within a "text" string. It improves upon the brute-force approach by avoiding unnecessary comparisons through preprocessing the pattern.
> 
> Assign me this issue.

@pankaj-bind it's already assigned to you. Please go ahead!

**Comment by hemanthhhhhh** [comment]
The KMP algorithm avoids redundant comparisons by preprocessing the pattern to determine where to continue searching from when a mismatch occurs. This preprocessing involves computing a prefix function (also known as the failure function), which indicates the longest proper prefix of the pattern that is also a suffix up to a given point.
Please assign me the issue

**Comment by Varuni2005** [comment]
Please assign this task to me
