### ISSUE TITLE
To Eligible for Hacktoberfest as maintainer

### ISSUE THREAD

**Issue by harshit1142** [Saloni6111/DSA_Problems-Hacktoberfest-2024#119]
Add CODE_OF_CONDUCT.md and CONTRIBUTING.md files to be eligible as a maintainer in Hacktoberfest

Refer : https://hacktoberfest.com/participation/#maintainers

**Comment by Saloni6111** [comment]
> Add CODE_OF_CONDUCT.md and CONTRIBUTING.md files to be eligible as a maintainer in Hacktoberfest
> 
> Refer : https://hacktoberfest.com/participation/#maintainers

@harshit1142  I think no need of this as I had added readme.md file with all details. 
If still you thinks it is needed will add that or if want to add i can assign to you.

**Comment by harshit1142** [comment]
@Saloni6111 I can add the required files.

**Comment by Saloni6111** [comment]
> @Saloni6111 I can add the required files.

@harshit1142 Sure, it's already assigned to you. Please go ahead!

**Comment by Ionfinisher** [comment]
Hello @Saloni6111 sir, my PR was excluded from Hactoberfest. What shall I do?

**Comment by Saloni6111** [comment]
> Hello @Saloni6111 sir, my PR was excluded from Hacktoberfest. What shall I do?

can I know which PR you are talking about?

**Comment by harshit1142** [comment]
@Saloni6111 
1.https://github.com/Saloni6111/DSA_Problems-Hacktoberfest-2024/pull/83
2.https://github.com/Saloni6111/DSA_Problems-Hacktoberfest-2024/pull/84
