### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#12]
write Insertion Sort Algorithm.

**Comment by Rana-Randeep** [comment]
Hi, @Saloni6111 I would like to take on this task and contribute. Could you please assign it to me?

**Comment by Saloni6111** [comment]
> Hi, @Saloni6111 I would like to take on this task and contribute. Could you please assign it to me?

@Rana-Randeep  Yes, it's already assigned to you. Please go ahead!

**Comment by Utkarsh-Aggarwal** [comment]
please assign this to  me my gfg profile https://www.geeksforgeeks.org/user/utkarshagbfsx/

**Comment by Sameeratweb** [comment]
please assign me this issue

**Comment by Rana-Randeep** [comment]
Hi, @Saloni6111 .Here is the link for PR ->  https://github.com/Saloni6111/DSA_Problems-Hacktoberfest-2024/pull/284.       Please verify it.

**Comment by Saloni6111** [comment]
merged!

**Comment by Rana-Randeep** [comment]
hi @Saloni6111 , On the hacktober dashboard , it is showing me that your repo is excluded.
