### ISSUE TITLE
N Queen Problem

### ISSUE THREAD

**Issue by Omji-Kesharwani** [Saloni6111/DSA_Problems-Hacktoberfest-2024#129]
Please assign me this issue

**Comment by hemanthhhhhh** [comment]
Please assign the issue & add the hacktoberfest label

**Comment by Saloni6111** [comment]
> Please assign me this issue

@Omji-Kesharwani N-Queen problems solution is already provided in java folder, I can assign you if you want to do in different language else will close this task, let me know

**Comment by Saloni6111** [comment]
> Please assign the issue & add the hacktoberfest label

@hemanthhhhhh you can create new issues with DSA problems which are not there already will assign those to you.

**Comment by Omji-Kesharwani** [comment]
why this pr has been excluded from hactoberfest
