### ISSUE TITLE
N-Queens Problem in Java

### ISSUE THREAD

**Issue by yashisrani** [Saloni6111/DSA_Problems-Hacktoberfest-2024#130]
The N-Queens Problem is a classic backtracking algorithm problem where the goal is to place N queens on an N×N chessboard such that no two queens threaten each other. A queen can attack horizontally, vertically, and diagonally, so the algorithm needs to ensure that no two queens share the same row, column, or diagonal.

I want to add algorithm code . please assign me ..

**Comment by hemanthhhhhh** [comment]
Would like to contribute .Please assign me
The N-Queens Problem is a classic combinatorial problem in computer science and mathematics, often used to illustrate algorithms involving backtracking, recursion, and constraint satisfaction. It involves placing N queens on an N×N chessboard such that no two queens threaten each other.

**Comment by Aditya-K477** [comment]
Please assign this issue to me. 
I want to make contribution to it.

**Comment by Aditya-K477** [comment]
And please add the hactoberfest lable

**Comment by Saloni6111** [comment]
> The N-Queens Problem is a classic backtracking algorithm problem where the goal is to place N queens on an N×N chessboard such that no two queens threaten each other. A queen can attack horizontally, vertically, and diagonally, so the algorithm needs to ensure that no two queens share the same row, column, or diagonal.
> 
> I want to add algorithm code . please assign me ..

@yashisrani N-Queen solution is already there in java folder you can create another issue with other DSA questions or can contribute in different language.
