### ISSUE TITLE
QickSort Algorithm 

### ISSUE THREAD

**Issue by Omji-Kesharwani** [Saloni6111/DSA_Problems-Hacktoberfest-2024#133]
Please Assign this issue to me

**Comment by Rajesh-1234567** [comment]
Hello !
Please Assign this issue to me.

**Comment by Saloni6111** [comment]
> Please Assign this issue to me

@Omji-Kesharwani assigned to you. Please go ahead!

**Comment by coderaadi1** [comment]
Please assign this issue

**Comment by llabhill** [comment]
hii @saloni6111 please assign me this issue

**Comment by Utkarsh-Aggarwal** [comment]
hi i am a second year student , paving my way into open source can please assign this issue to me @Saloni6111
