### ISSUE TITLE
Calculator in python

### ISSUE THREAD

**Issue by Aditya-K477** [Saloni6111/DSA_Problems-Hacktoberfest-2024#134]
Write a code to make calculator in python without using elif function

**Comment by Aditya-K477** [comment]
Please assign me this issue

**Comment by Saloni6111** [comment]
> Please assign me this issue

@Aditya-K477 Sure, it's already assigned to you. Please go ahead!

**Comment by MUDITJAINN** [comment]
Kindly assign me this issue

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will do your work

**Comment by Saloni6111** [comment]
@Aditya-K477 Merged!
