### ISSUE TITLE
Wildcard Matching

### ISSUE THREAD

**Issue by hemanthhhhhh** [Saloni6111/DSA_Problems-Hacktoberfest-2024#139]
Given an input string (s) and a pattern (p), implement wildcard pattern matching with support for '?' and '*' where:

'?' Matches any single character.
'*' Matches any sequence of characters (including the empty sequence).
The matching should cover the entire input string (not partial).

Example 1:

Input: s = "aa", p = "a"
Output: false
Explanation: "a" does not match the entire string "aa".

Example 2:

Input: s = "aa", p = "*"
Output: true
Explanation: '*' matches any sequence.

Example 3:

Input: s = "cb", p = "?a"
Output: false
Explanation: '?' matches 'c', but the second letter is 'a', which does not match 'b'.

**Comment by hemanthhhhhh** [comment]
Can you please contribute on this issue @Saloni6111

**Comment by Saloni6111** [comment]
> Can you please contribute on this issue @Saloni6111

@hemanthhhhhh assigned this to you!

**Comment by dauntless05** [comment]
can you assign the issue please?

**Comment by Saloni6111** [comment]
@hemanthhhhhh  merged!
