### ISSUE TITLE
LRU Cache 

### ISSUE THREAD

**Issue by Gowthamsai29** [Saloni6111/DSA_Problems-Hacktoberfest-2024#148]
**LRU (Least Recently Used) Cache** is a data structure that stores a limited number of items and removes the least recently accessed items when the cache reaches its limit. It is designed to optimize memory usage and access speed, ensuring frequently used data stays available.

### Uses:
- **Operating Systems**: Used in memory management to manage page replacements.
- **Databases**: Improves performance by caching frequently queried data.
- **Web Browsers**: Stores recently visited pages for faster reloading.
- **Mobile Apps**: Helps manage limited memory by caching important resources.

**Comment by Saloni6111** [comment]
> **LRU (Least Recently Used) Cache** is a data structure that stores a limited number of items and removes the least recently accessed items when the cache reaches its limit. It is designed to optimize memory usage and access speed, ensuring frequently used data stays available.
> 
> ### Uses:
> * **Operating Systems**: Used in memory management to manage page replacements.
> * **Databases**: Improves performance by caching frequently queried data.
> * **Web Browsers**: Stores recently visited pages for faster reloading.
> * **Mobile Apps**: Helps manage limited memory by caching important resources.

@Gowthamsai29 assigend to you, please proceed!

**Comment by Saloni6111** [comment]
@Gowthamsai29 Merged!
