### ISSUE TITLE
Middle of the Linked List

### ISSUE THREAD

**Issue by hemanthhhhhh** [Saloni6111/DSA_Problems-Hacktoberfest-2024#151]
Given the head of a singly linked list, return the middle node of the linked list.

If there are two middle nodes, return the second middle node.

Input: head = [1,2,3,4,5]
Output: [3,4,5]
Explanation: The middle node of the list is node 3.

Input: head = [1,2,3,4,5,6]
Output: [4,5,6]
Explanation: Since the list has two middle nodes with values 3 and 4, we return the second one.

**Comment by hemanthhhhhh** [comment]
Please let me contribute to the issue @Saloni6111

**Comment by Crimson-Muffin** [comment]
Can I please contribute to this DSA Problem ?

**Comment by Saloni6111** [comment]
> Can I please contribute to this DSA Problem ?

@Crimson-Muffin you can create your own DSA problem which is not there, I will assign that to you!

**Comment by Saloni6111** [comment]
> Please let me contribute to the issue @Saloni6111

@hemanthhhhhh Go-ahead!

**Comment by hemanthhhhhh** [comment]
@Saloni6111 the repository is not following values of hacktoberfest because of whuch no contribution made to this will be counted
