### ISSUE TITLE
Find the Alien Language Sequence

### ISSUE THREAD

**Issue by Astordnomer** [Saloni6111/DSA_Problems-Hacktoberfest-2024#153]
It Stored in a sequence based on their dependencies. Each character can only appear after all the characters on which it depends. You are Given a set of characters and their dependencies, and your task is to determine the correct order of characters in the alien language.
Can you Assign me.

**Comment by Saloni6111** [comment]
> It Stored in a sequence based on their dependencies. Each character can only appear after all the characters on which it depends. You are Given a set of characters and their dependencies, and your task is to determine the correct order of characters in the alien language. Can you Assign me.

@Astordnomer Assigned!

**Comment by Utkarsh-Aggarwal** [comment]
pleasen assign this issue to me @Saloni6111

**Comment by Saloni6111** [comment]
merged!
