### ISSUE TITLE
Swapping Nodes in a Linked List

### ISSUE THREAD

**Issue by Crimson-Muffin** [Saloni6111/DSA_Problems-Hacktoberfest-2024#157]
You are given the head of a linked list, and an integer k.

Return the head of the linked list after swapping the values of the kth node from the beginning and the kth node from the end 
(the list is 1-indexed).

Example 1 
Input : head = [1,2,3,4,5], k = 2
Output: [1,4,3,2,5]

Example 2
Input : head = [7,9,6,6,7,8,3,0,9,5], k = 5
Output: [7,9,6,6,8,7,3,0,9,5]

Can you assign this issue to me @Saloni6111

**Comment by Saloni6111** [comment]
> You are given the head of a linked list, and an integer k.
> 
> Return the head of the linked list after swapping the values of the kth node from the beginning and the kth node from the end (the list is 1-indexed).
> 
> Example 1 Input : head = [1,2,3,4,5], k = 2 Output: [1,4,3,2,5]
> 
> Example 2 Input : head = [7,9,6,6,7,8,3,0,9,5], k = 5 Output: [7,9,6,6,8,7,3,0,9,5]
> 
> Can you assign this issue to me @Saloni6111

@Crimson-Muffin Assigned, Go-ahead!

**Comment by dauntless05** [comment]
hi can you please assign me this issue

**Comment by Utkarsh-Aggarwal** [comment]
hi i am a second year student , paving my way into open source can please assign this issue to me @Saloni6111
