### ISSUE TITLE
Bridges in Graph - Using Tarjan's Algorithm

### ISSUE THREAD

**Issue by rishirohilla** [Saloni6111/DSA_Problems-Hacktoberfest-2024#158]
Problem Statement: There are n servers numbered from 0 to n - 1 connected by undirected server-to-server connections forming a network where connections[i] = [ai, bi] represents a connection between servers ai and bi. Any server can reach other servers directly or indirectly through the network.

A critical connection is a connection that, if removed, will make some servers unable to reach some other servers.

Return all critical connections in the network in any order.

**Comment by rishirohilla** [comment]
Kingly Please Assign me this issue

**Comment by Saloni6111** [comment]
> Kindly Please Assign me this issue

@rishirohilla Done!

**Comment by dauntless05** [comment]
hi kindly assign me this issue
