### ISSUE TITLE
Valid Parentheses

### ISSUE THREAD

**Issue by Rajesh-1234567** [Saloni6111/DSA_Problems-Hacktoberfest-2024#159]
Poblem Statement:  
Given a string containing just the characters `'('`, `')'`, `'{'`, `'}'`, `'['`, and `']'`, determine if the input string is valid. An input string is valid if:

1. Open brackets must be closed by the same type of brackets.
2. Open brackets must be closed in the correct order.

Example 1:  
Input : `s = "()"`  
Output : `true`

Example 2:  
input : `s = "()[]{}"`  
Output: `true`

Example 3:  
Input**: `s = "(]"`  
Output**: `false`

Constraints:  
- The string contains at most ( 10^4 ) characters.

**Comment by Rajesh-1234567** [comment]
Hey !
I have created this issue.
Can you please assign to me ?

**Comment by Saloni6111** [comment]
> Hey @Saloni6111 ! I have created this issue. Can you please assign to me ?

@Rajesh-1234567 Assigned, but this (valid Parentheses) code is already in-place. So, from next time please take care of these things and create issue with DSA problems which is not in this repo already.

**Comment by akashdas031** [comment]
Hi @Saloni6111 ,

I see that you opened this issue regarding the "Valid Parentheses" problem. I have implemented a solution and would like to contribute it to this repository.

You can find my code here: https://github.com/akashdas031/DSA/blob/main/leetCode/validParanthesis.java

I will create a pull request shortly. If you have any specific requirements or guidelines I should follow, please let me know!

Thanks!

**Comment by anshika-75** [comment]
i have created PR for ValidParenthesis #159 . Kindly Merge it @Rajesh-1234567
