### ISSUE TITLE
Articulation Point in Graph

### ISSUE THREAD

**Issue by rishirohilla** [Saloni6111/DSA_Problems-Hacktoberfest-2024#160]
Problem Statement: Given an undirected connected graph with V vertices and adjacency list adj. You are required to find all the vertices removing which (and edges through it) disconnect the graph into 2 or more components.

**Comment by rishirohilla** [comment]
Kindly Assign me this issue

**Comment by Saloni6111** [comment]
> Kindly please Assign me this issue

@rishirohilla Done!

**Comment by dauntless05** [comment]
hi please assign me this issue
