### ISSUE TITLE
Kosaraju's Algorithm

### ISSUE THREAD

**Issue by rishirohilla** [Saloni6111/DSA_Problems-Hacktoberfest-2024#161]
Problem Statement: Given a Directed Graph with V vertices (Numbered from 0 to V-1) and E edges, Find the number of strongly connected components in the graph.

**Comment by rishirohilla** [comment]
Kindly Please assign me this issue

**Comment by Saloni6111** [comment]
> Kindly Please assign me this issue

@rishirohilla Done!
