### ISSUE TITLE
Coin Change

### ISSUE THREAD

**Issue by Rajesh-1234567** [Saloni6111/DSA_Problems-Hacktoberfest-2024#162]
Problem Title: Coin Change

Problem Statement:
You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money. You want to determine the fewest number of coins that you need to make up that amount. If that amount cannot be made up by any combination of the coins, return -1.

You may assume that you have an infinite number of each kind of coin.

Write a function coinChange that returns the fewest number of coins needed to make up the given amount.

Example 1:
Input: coins = [1, 2, 5], amount = 11
Output: 3
Explanation: The minimum number of coins is 3 (11 = 5 + 5 + 1).

Example 2:
Input: coins = [2], amount = 3
Output: -1
Explanation: The amount cannot be made up using the available coins.

Example 3:
Input: coins = [1], amount = 0
Output: 0
Explanation: No coins are needed to make the amount.

Example 4:
Input: coins = [1], amount = 2
Output: 2
Explanation: The minimum number of coins is 2 (2 = 1 + 1).

Constraints:

1 <= coins.length <= 12
1 <= coins[i] <= 2^31 - 1
0 <= amount <= 10^4

**Comment by Rajesh-1234567** [comment]
Hey Saloni6111 !
can you please assign this task to me ?

**Comment by Saloni6111** [comment]
> Hey @Saloni6111 ! can you please assign this task to me ?

@Rajesh-1234567 Done!

**Comment by Rajesh-1234567** [comment]
@Saloni6111 please accept mt PR.
