### ISSUE TITLE
Minimum cost to cut the stick

### ISSUE THREAD

**Issue by rishirohilla** [Saloni6111/DSA_Problems-Hacktoberfest-2024#163]
Problem Description: We are given a stick of length N and a CUTS array of size C. The stick has markings as shown, and the CUTS array depicts the marking at which the stick needs to be cut (shown in red).

**Comment by rishirohilla** [comment]
Kindly please assign me this issue

**Comment by Saloni6111** [comment]
> Kindly please assign me this issue

@rishirohilla Done!

**Comment by Utkarsh-Aggarwal** [comment]
hi i am a second year student , paving my way into open source can please assign this issue to me @Saloni6111
