### ISSUE TITLE
Best Time to Buy and Sell Stock II

### ISSUE THREAD

**Issue by Rajesh-1234567** [Saloni6111/DSA_Problems-Hacktoberfest-2024#165]
Problem Statement:
You are given an array prices where prices[i] is the price of a given stock on the i-th day. You can buy and sell the stock as many times as you like, but you must sell the stock before you buy it again. Your goal is to maximize your profit.

Write a function maxProfit that calculates the maximum profit you can achieve from these transactions.

Example 1:
Input: prices = [7, 1, 5, 3, 6, 4]
Output: 7
Explanation:

Buy on day 2 (price = 1) and sell on day 3 (price = 5), profit = 5 - 1 = 4.
Buy on day 4 (price = 3) and sell on day 5 (price = 6), profit = 6 - 3 = 3.
Total profit = 4 + 3 = 7.
Example 2:
Input: prices = [1, 2, 3, 4, 5]
Output: 4
Explanation: Buy on day 1 (price = 1) and sell on day 5 (price = 5), total profit = 4.

Example 3:
Input: prices = [7, 6, 4, 3, 1]
Output: 0
Explanation: No transactions are done, and the max profit = 0.

Constraints:

1 <= prices.length <= 10^5
0 <= prices[i] <= 10^4

Hey @Saloni6111 !
can you please assign this task to me ?

**Comment by Rajesh-1234567** [comment]
Hey @Saloni6111 !
please assign this task to me.

**Comment by Saloni6111** [comment]
> Hey @Saloni6111 ! please assign this task to me. I have also committed the solution. I request to merge my solution. This is an unique problem solved by dynamic programming approach.

@Rajesh-1234567 Sure, it is assigned to you.

**Comment by Rajesh-1234567** [comment]
Please accept my merge request.
