### ISSUE TITLE
Unique Paths

### ISSUE THREAD

**Issue by PALASH2201** [Saloni6111/DSA_Problems-Hacktoberfest-2024#168]
There is a robot on an m x n grid. The robot is initially located at the top-left corner (i.e., grid[0][0]). The robot tries to move to the bottom-right corner (i.e., grid[m - 1][n - 1]). The robot can only move either down or right at any point in time.

Given the two integers m and n, return the number of possible unique paths that the robot can take to reach the bottom-right corner.

The test cases are generated so that the answer will be less than or equal to 2 * 109.

 Example 1:
 Input: m = 3, n = 7
 Output: 28
 
 Example 2:
Input: m = 3, n = 2
Output: 3
Explanation: From the top-left corner, there are a total of 3 ways to reach the bottom-right corner:
1. Right -> Down -> Down
2. Down -> Down -> Right
3. Down -> Right -> Down

Constraints:
1 <= m, n <= 100 

Please assign this to me. 
Leetcode Problem link : [https://leetcode.com/problems/unique-paths/description/?envType=problem-list-v2&envId=dynamic-programming](https://leetcode.com/problems/unique-paths/description/?envType=problem-list-v2&envId=dynamic-programming)

**Comment by Saloni6111** [comment]
> There is a robot on an m x n grid. The robot is initially located at the top-left corner (i.e., grid[0][0]). The robot tries to move to the bottom-right corner (i.e., grid[m - 1][n - 1]). The robot can only move either down or right at any point in time.
> 
> Given the two integers m and n, return the number of possible unique paths that the robot can take to reach the bottom-right corner.
> 
> The test cases are generated so that the answer will be less than or equal to 2 * 109.
> 
> Example 1: Input: m = 3, n = 7 Output: 28
> 
> Example 2: Input: m = 3, n = 2 Output: 3 Explanation: From the top-left corner, there are a total of 3 ways to reach the bottom-right corner:
> 
> 1. Right -> Down -> Down
> 2. Down -> Down -> Right
> 3. Down -> Right -> Down
> 
> Constraints: 1 <= m, n <= 100
> 
> Please assign this to me. Leetcode Problem link : https://leetcode.com/problems/unique-paths/description/?envType=problem-list-v2&envId=dynamic-programming

@PALASH2201 Assigned to you!

**Comment by dauntless05** [comment]
can you assign me this issue please

**Comment by Utkarsh-Aggarwal** [comment]
hi i am a second year student , paving my way into open source can please assign this issue to me @Saloni6111

**Comment by PALASH2201** [comment]
@Saloni6111  Your repo seems to be excluded from Hacktoberfest 2024. I came across this image
![image](https://github.com/user-attachments/assets/69451bf6-15e6-44ff-b296-f617590e6518)
I think DSA questions are not valid
