### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Aditya-K477** [Saloni6111/DSA_Problems-Hacktoberfest-2024#169]
@Saloni6111 it shows that this repo has been excluded from the hactoberfest please check on it. 
And it's showing all my contributions excluded.. 
Please help....

**Comment by Saloni6111** [comment]
> @Saloni6111 it shows that this repo has been excluded from the hactoberfest please check on it. And it's showing all my contributions excluded.. Please help....

let me hear from others also, if they are also facing same issue!

**Comment by Aditya-K477** [comment]
![image](https://github.com/user-attachments/assets/d416abb7-f64e-479a-9549-22f56f8d489b)

**Comment by Aditya-K477** [comment]
@Saloni6111 i have attached this issue

**Comment by Aditya-K477** [comment]
![image](https://github.com/user-attachments/assets/3938e7b2-6f4c-42ee-82e0-f90d12c6291b)

**Comment by Ash914027** [comment]
> @Saloni6111 it shows that this repo has been excluded from the hactoberfest please check on it. And it's showing all my contributions excluded.. Please help....

same problem
![Uploading Screenshot 2024-10-01 223956.png…]()
