### ISSUE TITLE
Single Number

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#17]
Given the array, Find the single number that appears only once?

**Comment by Brijeshthummar02** [comment]
sure i can work on this, assign me.

**Comment by dauntless05** [comment]
hi please assign this to me!!

**Comment by Utkarsh-Aggarwal** [comment]
please assign this to  me my gfg profile https://www.geeksforgeeks.org/user/utkarshagbfsx/
