### ISSUE TITLE
Depth-First Search (DFS)

### ISSUE THREAD

**Issue by MUDITJAINN** [Saloni6111/DSA_Problems-Hacktoberfest-2024#170]
Depth-First Search (DFS) is a graph traversal algorithm used to explore nodes and edges of a graph systematically. It starts at a selected node (often called the "source" or "root") and explores as far as possible along each branch before backtracking.

It is a foundational algorithm in computer science, with numerous applications in various fields, including artificial intelligence, networking, and pathfinding.

**Comment by MUDITJAINN** [comment]
@Saloni6111 Please Assign this issue to me.

**Comment by Saloni6111** [comment]
@MUDITJAINN Merged!

**Comment by MUDITJAINN** [comment]
@Saloni6111 Please assign the labels as hacktoberfest and hactkoberfest-accepted as this issue is not being counted as a contribution to this hacktoberfest 2024 event.  
![image](https://github.com/user-attachments/assets/d67c41e5-6267-484f-94d1-c7d402538777)
