### ISSUE TITLE
it's showing all my contributions excluded..

### ISSUE THREAD

**Issue by Ash914027** [Saloni6111/DSA_Problems-Hacktoberfest-2024#178]
@Saloni6111 it shows that this repo has been excluded from the hactoberfest please check on it.
And it's showing all my contributions excluded..
Please help..

**Comment by harshit1142** [comment]
@Saloni6111 it violates the Hacktoberfest rule as it is a collection and it get qualify as a project.

**Comment by Saloni6111** [comment]
> @Saloni6111 it violates the Hacktoberfest rule as it is a collection and it get qualify as a project.

@harshit1142 any idea how we can include again in hacktoberfest repos?

**Comment by harshit1142** [comment]
@Saloni6111, I don't have much knowledge about it. I guess it is a pure collection that's why got excluded.
join discord server: https://discord.com/invite/hacktoberfest

**Comment by Visha17** [comment]
same for me also.pls help
