### ISSUE TITLE
CONTRIBUTION LOST

### ISSUE THREAD

**Issue by Gowthamsai29** [Saloni6111/DSA_Problems-Hacktoberfest-2024#179]
@Saloni6111 
![image](https://github.com/user-attachments/assets/c47ff7fa-1a03-4a84-afcb-67c5e1fdf8ed)
Please look into it

**Comment by PALASH2201** [comment]
I am too facing this issue!

**Comment by Visha17** [comment]
I am too facing this issue!

pls look into it.

**Comment by Saloni6111** [comment]
> I am too facing this issue!
> 
> pls look into it.

@Visha17 Sorry, I'm not able to fix it.
I created new one go with [this](https://github.com/Saloni6111/DSA_POTD_Hacktoberfest2024) repo.

**Comment by Visha17** [comment]
ok.whether this repo is accepted by hacktoberfest?!

**Comment by Saloni6111** [comment]
> ok.whether this repo is accepted by hacktoberfest?!

yes!
