### ISSUE TITLE
Find the Maximum Element in an Array

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#18]
Given an array of integers, write a function to find and return the maximum element in the array. 
For example, in the array [3, 1, 4, 1, 5, 9], the maximum element is 9.

**Comment by Saloni6111** [comment]
> Hey @Saloni6111 I would like to take this up.

Sure, it's already assigned to you. Please go ahead!

**Comment by Sahil-Sinha-11** [comment]
Hey @Saloni6111 , I made a PR for the same.

**Comment by Saloni6111** [comment]
> Hey @Saloni6111 , I made a PR for the same.

merged  :)
