### ISSUE TITLE
Java Stream API Coding Interview Question 

### ISSUE THREAD

**Issue by Spardha-hash** [Saloni6111/DSA_Problems-Hacktoberfest-2024#184]
How to find duplicate elements in a given integers list in java using Stream functions?

Input 1 : 
arr[] = [10,15,8,49,25,98,98,32,15]
Output : 98, 15

Input 2 : 
arr[] = [1, 1, 85, 6, 2, 3, 65, 6, 45, 45, 5662, 2582, 2, 266, 666, 656]
Output : 1 6 2 45

Hi @Saloni6111,
This was one of the question that was asked to me in Interview. I am raising the issue for it to add this in your respository. Please assign this issue to me.

**Comment by Saloni6111** [comment]
> How to find duplicate elements in a given integers list in java using Stream functions?
> 
> Input 1 : arr[] = [10,15,8,49,25,98,98,32,15] Output : 98, 15
> 
> Input 2 : arr[] = [1, 1, 85, 6, 2, 3, 65, 6, 45, 45, 5662, 2582, 2, 266, 666, 656] Output : 1 6 2 45
> 
> Hi @Saloni6111, This was one of the question that was asked to me in Interview. I am raising the issue for it to add this in your respository. Please assign this issue to me.

@Spardha-hash Assigned to you!
