### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by pratikj697** [Saloni6111/DSA_Problems-Hacktoberfest-2024#185]
In this problem n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.
Input: height = [4,2,0,3,2,5]
Output: 9
The water trapped at index 2 is 3 units, at index 3 is 1 unit, and at index 4 is 2 units, so total is 9 units.

Input: height = [1, 0, 2]
Output: 1
n == height.length
1 <= n <= 2 * 10^4
0 <= height[i] <= 10^5 

Can you please assign this problem to me @Saloni6111.

**Comment by Deepikakolli4** [comment]
Hello @Saloni6111,

Could you kindly assign this task to me under Hacktoberfest? I look forward to completing it and submitting a merge request. Thank you!

**Comment by Saloni6111** [comment]
> In this problem n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining. Input: height = [4,2,0,3,2,5] Output: 9 The water trapped at index 2 is 3 units, at index 3 is 1 unit, and at index 4 is 2 units, so total is 9 units.
> 
> Input: height = [1, 0, 2] Output: 1 n == height.length 1 <= n <= 2 * 10^4 0 <= height[i] <= 10^5
> 
> Can you please assign this problem to me @Saloni6111.

@pratikj697 assigned!

**Comment by Saloni6111** [comment]
merged!
