### ISSUE TITLE
Implement Queue using Stack

### ISSUE THREAD

**Issue by naresh04122005** [Saloni6111/DSA_Problems-Hacktoberfest-2024#186]
Problem Statement: Given a Stack having some elements stored in it. Can you implement a
Queue using the given Stack?

Queue: A Queue is a linear data structure that works on the basis of FIFO(First in First out). This means the element added at first will be removed first from the Queue.

**Comment by naresh04122005** [comment]
please assign me this issue

**Comment by Utkarsh-Aggarwal** [comment]
please assign this issue to me @Saloni6111

**Comment by Saloni6111** [comment]
> please assign me this issue

@naresh04122005 assigned!
