### ISSUE TITLE
Morris Preorder Traversal of a Binary Tree

### ISSUE THREAD

**Issue by naresh04122005** [Saloni6111/DSA_Problems-Hacktoberfest-2024#187]
Problem Statement: Given a Binary Tree, implement Morris Preorder Traversal and return the array containing its preorder sequence.

Morris Preorder Traversal is a tree traversal algorithm aiming to achieve a space complexity of O(1) without recursion or an external data structure. The algorithm should efficiently visit each node in the binary tree in preorder sequence, printing or processing the node values as it traverses, without using a stack or recursion.

**Comment by naresh04122005** [comment]
please assign this issue to me

**Comment by Utkarsh-Aggarwal** [comment]
i am 2nd year student paving  my way to open source .please assign it to me

**Comment by Saloni6111** [comment]
> please assign this issue to me

@naresh04122005 assigned!
