### ISSUE TITLE
Remove Duplicates from an Array

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#19]
Write a function that takes an array of integers and removes any duplicate values, returning a new array. 
For example, from the array [1, 2, 2, 3, 4, 4], the output should be [1, 2, 3, 4].

**Comment by Ionfinisher** [comment]
Hi @Saloni6111 ,

I came across this issue and would love to contribute. This is my first time contributing to this project, but I have some experience in DSA with Python. Could you please assign me this issue? I’d be happy to work on it.

Thank you!

**Comment by Saloni6111** [comment]
> Hi @Saloni6111 ,
> 
> I came across this issue and would love to contribute. This is my first time contributing to this project, but I have some experience in DSA with Python. Could you please assign me this issue? I’d be happy to work on it.
> 
> Thank you!

Sure, it's already assigned to you. Please go ahead!

**Comment by Ionfinisher** [comment]
Thanks
