### ISSUE TITLE
Add greetings

### ISSUE THREAD

**Issue by chaanakyaaM** [Saloni6111/DSA_Problems-Hacktoberfest-2024#194]
![image](https://github.com/user-attachments/assets/ca7c555f-2503-4b98-8066-5cdc1f214b5a)

i would like to add the greetings message when a issue is created,
- This feature makes  your repo more professional.
- maintain communication with new users.
- makes new users easy to contribute.

**Comment by ShehzadAhm** [comment]
Hi @chaanakyaaM, can you assign this issue?

**Comment by Saloni6111** [comment]
> ![image](https://private-user-images.githubusercontent.com/131477601/372752300-ca7c555f-2503-4b98-8066-5cdc1f214b5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjEzMjYsIm5iZiI6MTcyNzg2MTAyNiwicGF0aCI6Ii8xMzE0Nzc2MDEvMzcyNzUyMzAwLWNhN2M1NTVmLTI1MDMtNGI5OC04MDY2LTVjZGMxZjIxNGI1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwOTIzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzUyNzlkMTZmYWM2MGY3ZTQ5YzJjZWNjMDkyYzA2MDUxZDZhY2M1NjlkYmM2OWMwNzM5N2IyY2NiYzk4NWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s4Dzkjumitxe6KPy7dxD4ShskxozvkVx5RFixcFvcKA)
> 
> i would like to add the greetings message when a issue is created,
> 
> * This feature makes  your repo more professional.
> * maintain communication with new users.
> * makes new users easy to contribute.

@chaanakyaaM 
It will be great please go ahead!, I had created one new repo for hacktoberfest I want this there as well, will create one issue for this can you comment in that issue so that I will assign that also to you?

**Comment by chaanakyaaM** [comment]
can you mention the repo link

**Comment by Saloni6111** [comment]
> can you mention the repo link

https://github.com/Saloni6111/DSA_POTD_Hacktoberfest2024/issues
