### ISSUE TITLE
Median of two sorted arrays (Hard)

### ISSUE THREAD

**Issue by chaanakyaaM** [Saloni6111/DSA_Problems-Hacktoberfest-2024#195]
**Problem statement:**
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

The overall run time complexity should be O(log (m+n)).

**Example 1:**

Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000
Explanation: merged array = [1,2,3] and median is 2.

**Example 2:**

Input: nums1 = [1,2], nums2 = [3,4]
Output: 2.50000
Explanation: merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.
 

**Constraints:**

nums1.length == m
nums2.length == n
0 <= m <= 1000
0 <= n <= 1000
1 <= m + n <= 2000
-106 <= nums1[i], nums2[i] <= 106

This hard problem covers topics such as Array, Binary Search and
 Divide and Conquer

**Comment by Visha17** [comment]
Can u assign me this problem?

**Comment by Aastha7078** [comment]
I want to work in this issue @chaanakyaaM ,could u pls assign it to me ?

**Comment by Ayush-Garg1** [comment]
Hello @Saloni6111,
Please assign this issue to me.
I will provide you with all the 3 approaches (i.e brute,better, and optimal)
