### ISSUE TITLE
Sorted Linked List to BST

### ISSUE THREAD

**Issue by Utkarsh-Aggarwal** [Saloni6111/DSA_Problems-Hacktoberfest-2024#196]
Difficulty: Hard
Accuracy: 53.24%
Given a Singly Linked List which has data members sorted in ascending order. Construct a Balanced Binary Search Tree which has same data members as the given Linked List.
Note: There might be nodes with the same value.

Examples:

Input: Linked List: 1->2->3->4->5->6->7

Output: 4 2 1 3 6 5 7
Explanation : The BST formed using elements of the linked list is -
        4
      /   \
     2     6
   /  \   / \
  1   3  5   7  
Hence, preorder traversal of this tree is 4 2 1 3 6 5 7
Input: Linked List : 1->2->3->4
 
Ouput: 3 2 1 4
Explanation: The BST formed using elements of the linked list is -

Hence, the preorder traversal of this tree is 3 2 1 4
Expected Time Complexity: O(n)
Expected Auxiliary Space: O(n)
 
Constraints:
1 ≤ Number of Nodes ≤ 106
1 ≤ Value of each node ≤ 106

**Comment by Utkarsh-Aggarwal** [comment]
kindly assign me this issue under hactoberfest 2024

**Comment by Saloni6111** [comment]
> Difficulty: Hard Accuracy: 53.24% Given a Singly Linked List which has data members sorted in ascending order. Construct a Balanced Binary Search Tree which has same data members as the given Linked List. Note: There might be nodes with the same value.
> 
> Examples:
> 
> Input: Linked List: 1->2->3->4->5->6->7
> 
> Output: 4 2 1 3 6 5 7 Explanation : The BST formed using elements of the linked list is - 4 / 2 6 / \ / 1 3 5 7 Hence, preorder traversal of this tree is 4 2 1 3 6 5 7 Input: Linked List : 1->2->3->4
> 
> Ouput: 3 2 1 4 Explanation: The BST formed using elements of the linked list is -
> 
> Hence, the preorder traversal of this tree is 3 2 1 4 Expected Time Complexity: O(n) Expected Auxiliary Space: O(n)
> 
> Constraints: 1 ≤ Number of Nodes ≤ 106 1 ≤ Value of each node ≤ 106

@Utkarsh-Aggarwal Assigned to you!

**Comment by Utkarsh-Aggarwal** [comment]
kindly accept my PR
