### ISSUE TITLE
Two Sum Problem

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#2]
Description: You will be given an array and target sum as input, you have to print two indices such that sum of values at that indices is equal to the given target.

write code for the above given problem.

**Comment by NidhiNayak08** [comment]
i would like to do this!

**Comment by Rana-Randeep** [comment]
Hi, @Saloni6111                                                                                                                                                                                       I would love to take on this task and contribute. Could you please assign it to me?

**Comment by Saloni6111** [comment]
> Rana-Randeep

sure, go ahead

**Comment by DevendraJaiswal074** [comment]
Hii, @Saloni6111 
I am a beginner. Could you please assign it to me?

**Comment by dauntless05** [comment]
hi please assign this to me!!

**Comment by Saloni6111** [comment]
merged!
