### ISSUE TITLE
Print Fibonacci Sequence

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#20]
Implement a function that prints the first n numbers in the Fibonacci sequence, where n is a positive integer provided as input. 

For example, for n = 5, the output should be 0, 1, 1, 2, 3.

**Comment by raxvab** [comment]
Hi @Saloni6111  Can you please assign it to me 
Here's my leetcode:-https://leetcode.com/u/whyybhav/

since this is my first time participating hence I'm learning how to contribute and stuff.

**Comment by Saloni6111** [comment]
> Hi @Saloni6111 Can you please assign it to me Here's my leetcode:-https://leetcode.com/u/whyybhav/
> 
> since this is my first time participating hence I'm learning how to contribute and stuff.

@raxvab  Sure, it's already assigned to you. Please go ahead!

**Comment by DevendraJaiswal074** [comment]
Hii @Saloni6111 
I'd love the opportunity to tackle this issue. Could you assign me to solve it?

**Comment by parthib2004** [comment]
Please assign this to me!

**Comment by dauntless05** [comment]
hi can you please assign it to me!!

**Comment by Utkarsh-Aggarwal** [comment]
please assign this to  me my gfg profile https://www.geeksforgeeks.org/user/utkarshagbfsx/

**Comment by Sameeratweb** [comment]
please it will be helpful if you assign it to me

**Comment by abhinandanmittal** [comment]
Hii  @Saloni6111 I have solved it in c++ language . please have a look  on  Pull request #253
