### ISSUE TITLE
Group anagram question

### ISSUE THREAD

**Issue by v-280** [Saloni6111/DSA_Problems-Hacktoberfest-2024#200]
This issue aims to add a coding problem titled "Group Anagrams" along with its solution to the repository.

### **PROBLEM STATEMENT**
Given an array of strings strs, group the anagrams together. You can return the answer in any order.

 

Example 1:

Input: strs = ["eat","tea","tan","ate","nat","bat"]

Output: [["bat"],["nat","tan"],["ate","eat","tea"]]

Explanation:

There is no string in strs that can be rearranged to form "bat".
The strings "nat" and "tan" are anagrams as they can be rearranged to form each other.
The strings "ate", "eat", and "tea" are anagrams as they can be rearranged to form each other.
Example 2:

Input: strs = [""]

Output: [[""]]

Constraints:

1 <= strs.length <= 104
0 <= strs[i].length <= 100
strs[i] consists of lowercase English letters.

_**I would like to contribute to this repo under hacktoberfest, kindly assign me this issue**_

**Comment by Anket08042003** [comment]
To solve the Group Anagrams problem, follow these steps:

1. Understand the Problem:
   - Group words that are anagrams, i.e., strings that can be rearranged to form the same word (e.g., "eat" and "tea").

2. Strategy:
   - Use a **character signature** for each word by sorting the characters. Anagrams will have the same sorted result.
   - For each word, sort its characters, then use the sorted word as a key to group the original words in a dictionary.

3. **Process**:
   - For each word in the input list:
     - Sort the word's characters to create a "signature".
     - Group words with the same signature together.
  
4. Output:
   - Collect and return the grouped anagrams from the dictionary as a list of lists.

This approach efficiently groups anagrams by utilizing the sorted signature as the key.

kindly assign this issue to me

**Comment by anshika-75** [comment]
I have Created PR for #200 @v-280 kindly merge it

**Comment by Saloni6111** [comment]
> This issue aims to add a coding problem titled "Group Anagrams" along with its solution to the repository.
> 
> ### **PROBLEM STATEMENT**
> Given an array of strings strs, group the anagrams together. You can return the answer in any order.
> 
> Example 1:
> 
> Input: strs = ["eat","tea","tan","ate","nat","bat"]
> 
> Output: [["bat"],["nat","tan"],["ate","eat","tea"]]
> 
> Explanation:
> 
> There is no string in strs that can be rearranged to form "bat". The strings "nat" and "tan" are anagrams as they can be rearranged to form each other. The strings "ate", "eat", and "tea" are anagrams as they can be rearranged to form each other. Example 2:
> 
> Input: strs = [""]
> 
> Output: [[""]]
> 
> Constraints:
> 
> 1 <= strs.length <= 104 0 <= strs[i].length <= 100 strs[i] consists of lowercase English letters.
> 
> _**I would like to contribute to this repo under hacktoberfest, kindly assign me this issue**_

@v-280 Assigned to you!

**Comment by v-280** [comment]
@Saloni6111 does this question assigned to someone else?
