### ISSUE TITLE
Coin Change Problem

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#21]
you are given an array of coin denominations, and a total amount. Your task is to determine the minimum number of coins needed to make that amount. You can use each coin denomination as many times as needed. If it is not possible to make the amount with the given denominations, return -1.

Example:
Input: coins = [1, 2, 5], amount = 11
Output: 3
Explanation: One possible way to make 11 is using two 5 coins and one 1 coin (5 + 5 + 1 = 11), which requires a total of 3 coins.

**Comment by raxvab** [comment]
Hi @Saloni6111  Can you please assign it to me 
Here's my leetcode:-https://leetcode.com/u/whyybhav/

**Comment by Saloni6111** [comment]
> Hi @Saloni6111 Can you please assign it to me Here's my leetcode:-https://leetcode.com/u/whyybhav/

@raxvab Yes, it's already assigned to you. Please go ahead!

**Comment by raxvab** [comment]
Hi @Saloni6111 
Raised one PR related to the same please review.
raxvab:coin_change_problem

**Comment by dauntless05** [comment]
hi can please assign it to me !!
thanks

**Comment by Saloni6111** [comment]
merged!
