### ISSUE TITLE
C code to make a queue.

### ISSUE THREAD

**Issue by Vibhav-Sharma** [Saloni6111/DSA_Problems-Hacktoberfest-2024#218]
Implement a Queue using a Doubly Linked List

You are required to implement a queue data structure using a doubly linked list. Your implementation should support the following operations:

Enqueue: Add an element to the rear of the queue.
Dequeue: Remove and return the element from the front of the queue.
Print: Display the current elements in the queue from front to rear.
Input Format:

The first line contains an integer 
𝑛
n representing the number of elements to enqueue.
The second line contains 
𝑛
n space-separated integers representing the elements to be added to the queue.
Output Format:

After enqueuing all elements, print the queue.
Dequeue all elements and print each dequeued element.
Finally, print the queue again, which should now be empty.

**Comment by Vibhav-Sharma** [comment]
@Saloni6111 please assign me this, and give the label too

**Comment by Saloni6111** [comment]
> @Saloni6111 please assign me this, and give the label too

done!
