### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#22]
Implement a binary search algorithm to find the index of a specific element in a sorted array. 
Given the sorted array, your task is to locate the index of the given number.

**Comment by Sahil-Sinha-11** [comment]
hey @Saloni6111 i would like to take this up next

**Comment by Sahil-Sinha-11** [comment]
hey @Saloni6111 I would like to take this next.

**Comment by raxvab** [comment]
Hi @Saloni6111  Can you please assign it to me 
Here's my leetcode:-https://leetcode.com/u/whyybhav/

**Comment by Saloni6111** [comment]
> hey @Saloni6111 I would like to take this next.

@Sahil-Sinha-11 it's already assigned to you. Please go ahead!

**Comment by Sahil-Sinha-11** [comment]
hey @Saloni6111 I made a pr for this

**Comment by Saloni6111** [comment]
> hey @Saloni6111 I made a pr for this



> hey @Saloni6111 I made a pr for this

merged!
