### ISSUE TITLE
Addition of Linked List Folder/File

### ISSUE THREAD

**Issue by OneLimeStudio** [Saloni6111/DSA_Problems-Hacktoberfest-2024#228]
I would like to add linked lists with basic  functions such as insertion, deletion , insert at last , find middle , etc under C

Please assign me this under hactoberfest label

**Comment by Saloni6111** [comment]
> I would like to add linked lists with basic functions such as insertion, deletion , insert at last , find middle , etc under C
> 
> Please assign me this under hactoberfest label

@OneLimeStudio done!
