### ISSUE TITLE
Printing Pascals's Triangle 

### ISSUE THREAD

**Issue by Sameeratweb** [Saloni6111/DSA_Problems-Hacktoberfest-2024#230]
You are given an integer N. Your task is to return a 2-D ArrayList containing the pascal’s triangle till the row N.

A Pascal's triangle is a triangular array constructed by summing adjacent elements in preceding rows. Pascal's triangle contains the values of the binomial coefficient. For example in the figure below.

For example, given integer N= 4 then you have to print.
1  
1 1 
1 2 1 
1 3 3 1

Here for the third row, you will see that the second element is the summation of the above two-row elements i.e. 2=1+1, and similarly for row three 3 = 1+2 and 3 = 1+2.

Expected Output:
Output:
1
1 1
1 2 1
1 3 3 1
1 4 6 4 1

**Comment by Sameeratweb** [comment]
please assign me with this issue

**Comment by Saloni6111** [comment]
> please assign me with this issue

done!
