### ISSUE TITLE
Detecting a cycle in a Linked list

### ISSUE THREAD

**Issue by Speedysays01** [Saloni6111/DSA_Problems-Hacktoberfest-2024#231]
This is one of the classic DSA questions. I can give its solution using Floyed's cycle detection algorithm(Tortoise and Hare). I'll be using C++ for it.
Please assign me this issue under the tag of Hacktoberfest 2024.

**Comment by Saloni6111** [comment]
> This is one of the classic DSA questions. I can give its solution using Floyed's cycle detection algorithm(Tortoise and Hare). I'll be using C++ for it. Please assign me this issue under the tag of Hacktoberfest 2024.

assigned!

**Comment by AnshDwivedi03** [comment]
can you assign it to me @Saloni6111

**Comment by Speedysays01** [comment]
@Saloni6111 Just created a pull request for it! Thank you for assigning me this.

**Comment by Saloni6111** [comment]
merged!

**Comment by Speedysays01** [comment]
Great! Thanks!
