### ISSUE TITLE
 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by garvit0908** [Saloni6111/DSA_Problems-Hacktoberfest-2024#233]
This is the standard dsa problem and i will be solving it using c++.Kindly assign me this issue under hacktober fest 2024.

**Comment by AnshDwivedi03** [comment]
Hey.., @Saloni6111 can you assign it to me

**Comment by Saloni6111** [comment]
> This is the standard dsa problem and i will be solving it using c++.Kindly assign me this issue under hacktober fest 2024.

@garvit0908 assigned to you!
