### ISSUE TITLE
Implement Queue using Stack

### ISSUE THREAD

**Issue by ShehzadAhm** [Saloni6111/DSA_Problems-Hacktoberfest-2024#235]
I would like to add this problem in Java.

Can you assign it to me with **hacktoberfest** label?

**Comment by Saloni6111** [comment]
> I would like to add this problem in Java.
> 
> Can you assign it to me with **hacktoberfest** label?

@ShehzadAhm done!

**Comment by ShehzadAhm** [comment]
Hi @Saloni6111, PR - https://github.com/Saloni6111/DSA_Problems-Hacktoberfest-2024/pull/244

**Comment by Saloni6111** [comment]
merged!
