### ISSUE TITLE
Binary Search Tree

### ISSUE THREAD

**Issue by VikrantKadam028** [Saloni6111/DSA_Problems-Hacktoberfest-2024#239]
I would like to add Binary Search Tree with basic functions such as insertion, deletion , insert at last , find middle using C++.
Please assign me this under hactoberfest 2024 Label :)

**Comment by Saloni6111** [comment]
@VikrantKadam028 assigned!

**Comment by ArcheR1901** [comment]
Hi I would like to contribute on this issue in java and C. Please assign me
