### ISSUE TITLE
Special Matrix Problem in C++

### ISSUE THREAD

**Issue by Amisha2093** [Saloni6111/DSA_Problems-Hacktoberfest-2024#243]
### Special Matrix Problem

**Problem Description:**

A matrix is called special if the sum of each row and the sum of each column is the same. Given a square matrix A of dimensions N×N. Find the minimum number of operations required to make it special. In one operation you can choose any number in the matrix and increase it by 1.

**Comment by Amisha2093** [comment]
Hi @Saloni6111,

Please assign this issue to me, under **hacktoberfest24**.

**Comment by Amisha2093** [comment]
Hi @Saloni6111,

I have added a new problem **Special Matrix in C++**, please review and merge my PR #245 under **hacktoberfest24**.

**Comment by Charul00** [comment]
can you assign to me

**Comment by Saloni6111** [comment]
merged!
