### ISSUE TITLE
Kahn's Algorithm Topological Sort

### ISSUE THREAD

**Issue by pravin435916** [Saloni6111/DSA_Problems-Hacktoberfest-2024#247]
I would like to add Topological sort algorithm using C++.
Please assign me this under Octoberfest 2024 Label :) and good first issue
1. using a stack to find the topological sort
2. using Kahn's algorithm to find the topological sort

**Comment by pravin435916** [comment]
@Saloni6111  can you assign this issue to me with hactoberfest label .

**Comment by Saloni6111** [comment]
> @Saloni6111 can you assign this issue to me with hactoberfest label .

assigned!
