### ISSUE TITLE
Next Greater Element

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#25]
Given an array, find the next greater element for each element in the array. The next greater element for an element is the first greater element to the right of it in the array.

**Comment by Brijeshthummar02** [comment]
@Saloni6111 assign me the issue.

**Comment by Saloni6111** [comment]
> @Saloni6111 assign me the issue.

@Brijeshthummar02 Sure, it's already assigned to you. Please go ahead!
