### ISSUE TITLE
Majority Element

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#26]
Given an array of size n, find the majority element. The majority element is the element that appears more than n/2 times.

**Comment by Brijeshthummar02** [comment]
hello @Saloni6111 i'm working on this.

**Comment by Saloni6111** [comment]
> hello @Saloni6111 i'm working on this.

@Brijeshthummar02 Sure, it's already assigned to you. Please go ahead!

**Comment by Brijeshthummar02** [comment]
Hi @Saloni6111 ,

I have all my solutions ready. I’ll be creating a pull request on October 1-2 when Hacktoberfest starts, so I can claim it.

Thanks!

**Comment by Saloni6111** [comment]
> Hi @Saloni6111 ,
> 
> I have all my solutions ready. I’ll be creating a pull request on October 1-2 when Hacktoberfest starts, so I can claim it.
> 
> Thanks!

okay!

**Comment by Brijeshthummar02** [comment]
please put hacktoberfest accepted on all my pull request.
