### ISSUE TITLE
Sprial Matrix using cpp

### ISSUE THREAD

**Issue by iamkaniska** [Saloni6111/DSA_Problems-Hacktoberfest-2024#263]
@Saloni6111 assign me this issue for hactoberfest

**Comment by rahul-chakradhari** [comment]
@Saloni6111 mam i had solved this question today only please assgin it to me

**Comment by Saloni6111** [comment]
> @Saloni6111 assign me this issue for hactoberfest

done!

**Comment by rahul-chakradhari** [comment]
@Saloni6111 please assign this to me also mam
