### ISSUE TITLE
Cycle Detection in a Linked List

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#28]
Given a linked list, check if there is a cycle in it.

**Comment by Vishrut99** [comment]
i will solve this problem By using 2 Pointers one is fast and other is slow (Totrtoise Hare method).with O(n) time complexity and constant space.

**Comment by Saloni6111** [comment]
> i will solve this problem By using 2 Pointers one is fast and other is slow (Totrtoise Hare method).with O(n) time complexity and constant space.

@Vishrut99 Please go ahead!
