### ISSUE TITLE
Sorting Linked List Problem in C++

### ISSUE THREAD

**Issue by pulkitgarg04** [Saloni6111/DSA_Problems-Hacktoberfest-2024#280]
Hi @Saloni6111, I would like to implement the Sorting in Linked Lists problem using C++ as part of this repository. The solution will sort the linked list using an efficient algorithm and return the sorted list.

Can you please assign this issue to me under Hacktoberfest-2024? Thank you!

**Comment by DevendraJaiswal074** [comment]
hii @Saloni6111 
I want to solve this issue, Could you assign me?

**Comment by Saloni6111** [comment]
> Hi @Saloni6111, I would like to implement the Sorting in Linked Lists problem using C++ as part of this repository. The solution will sort the linked list using an efficient algorithm and return the sorted list.
> 
> Can you please assign this issue to me under Hacktoberfest-2024? Thank you!

done!

**Comment by AbhishekSAngadi** [comment]
i want to solve...
