### ISSUE TITLE
Find Peak Element

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#29]
A peak element is an element that is strictly greater than its neighbors. Given an integer array, find a peak element and return its index.

**Comment by Vishrut99** [comment]
Implement Binary Search Algorithm to find out the peak elements in a sorted array with time complexity of O(nlogn) and space Complexity of O(1)

**Comment by Saloni6111** [comment]
> Implement Binary Search Algorithm to find out the peak elements in a sorted array with time complexity of O(nlogn) and space Complexity of O(1).So I would like to contribute in this issue.

@Vishrut99 Sure, it's already assigned to you. Please go ahead!

**Comment by Saloni6111** [comment]
resolved by @Vishrut99
