### ISSUE TITLE
Implement Different Types of Linked Lists and Operations

### ISSUE THREAD

**Issue by prasadsarwar** [Saloni6111/DSA_Problems-Hacktoberfest-2024#294]
I would like to contribute by implementing different types of linked lists along with basic and advanced operations in C/C++. The linked lists and operations are as follows:

Linked List Types:
Singly Linked List (SLL)
Singly Circular Linked List (SCLL)
Doubly Linked List (DLL)
Doubly Circular Linked List (DCLL)
Operations:
Basic: Insert, Delete, Display.
Advanced: Search, Sort, Reverse, Count nodes, Detect loops.
Proposed Approach:

Implement each linked list in separate files.
Add basic operations first, followed by advanced operations.
Language: C/C++

This contribution will enhance the repo's data structure implementations, making it more comprehensive for developers.

**Comment by prasadsarwar** [comment]
Kindly assign this issue to me. I’m eager to contribute and implement these features.

**Comment by ArcheR1901** [comment]
Hi, I have already added a code in C folder, a randomized quick sort. will there be any issues or that will be accepted for Hactoberfest 2024? If there is any issue, please let me know, I will make the necessary changes.
