### ISSUE TITLE
Make Sum Divisible by P

### ISSUE THREAD

**Issue by Saumitra11** [Saloni6111/DSA_Problems-Hacktoberfest-2024#297]
Given an array of positive integers nums, remove the smallest subarray (possibly empty) such that the sum of the remaining elements is divisible by p. It is not allowed to remove the whole array.

Return the length of the smallest subarray that you need to remove, or -1 if it's impossible.

A subarray is defined as a contiguous block of elements in the array.

Hi @Saloni6111 
This is LeetCode Problem 1590 (Problem of the Day for 3/10/24): https://leetcode.com/problems/make-sum-divisible-by-p/description/

Could you please assign this to me?

**Comment by harshitkumargupta** [comment]
Hello @Saloni6111 
I’d like to take on this issue and contribute towards resolving it. Could you please assign it to me? I’ll make sure to keep you updated as I progress.

**Comment by Saumitra11** [comment]
https://github.com/Saloni6111/DSA_Problems-Hacktoberfest-2024/pull/301

Hi @Saloni6111 I've raised the PR, could you please take a look.
