### ISSUE TITLE
Find the Missing Number

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#31]
Given an array containing n distinct numbers taken from 0, 1, 2, ..., n, find the one that is missing.

**Comment by faresbouzayen** [comment]
Hi @Saloni6111,

I'd like to work on this issue! I'll implement a solution using the sum formula to find the missing number in O(n) time. 

Thanks!

**Comment by Saloni6111** [comment]
> Hi @Saloni6111,
> 
> I'd like to work on this issue! I'll implement a solution using the sum formula to find the missing number in O(n) time.
> 
> Thanks!

@faresbouzayen Sure, it's already assigned to you. Please go ahead!

**Comment by Utkarsh-Aggarwal** [comment]
please assign this to  me my gfg profile https://www.geeksforgeeks.org/user/utkarshagbfsx/ @Saloni6111
