### ISSUE TITLE
Merge Two Sorted Arrays

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#32]
Given two sorted arrays, merge them into a single sorted array without using extra space.

**Comment by faresbouzayen** [comment]
Hi @Saloni6111,

I'd like to work on this issue! I'll implement a two-pointer solution to merge the two arrays without using extra space.

Thanks!

**Comment by Saloni6111** [comment]
> Hi @Saloni6111,
> 
> I'd like to work on this issue! I'll implement a two-pointer solution to merge the two arrays without using extra space.
> 
> Thanks!

@faresbouzayen Sure, it's already assigned to you. Please go ahead!

**Comment by dauntless05** [comment]
hi @Saloni6111 
can you please assign the issue to me

**Comment by Utkarsh-Aggarwal** [comment]
please assign this to  me my gfg profile https://www.geeksforgeeks.org/user/utkarshagbfsx/ @Saloni6111
