### ISSUE TITLE
Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#34]
Given two sorted arrays, find the median of the two sorted arrays. The overall run time complexity should be O(log (m+n)).

**Comment by byhlel** [comment]
Hello, could you assign this to me?

**Comment by Prax860** [comment]
hi , could you assign this to me?

**Comment by Saloni6111** [comment]
> hi , could you assign this to me?

@Prax860 Sure, it's already assigned to you. Please go ahead!
