### ISSUE TITLE
Find the Duplicate Number

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#35]
Given an array of integers containing n + 1 integers where each integer is in the range [1, n] inclusive, find the duplicate number.

**Comment by byhlel** [comment]
Hello, could you assign this to me?

**Comment by DevendraJaiswal074** [comment]
hello @Saloni6111 
i am beginner , could you assign me this issue

**Comment by Saloni6111** [comment]
> hello @Saloni6111 i am beginner , could you assign me this issue

@DevendraJaiswal074 Sure, it's already assigned to you. Please go ahead!
