### ISSUE TITLE
Valid Parentheses

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#37]
Given a string containing just the characters '(', ')', '{', '}', '[', ']', determine if the input string is valid.

**Comment by llabhill** [comment]
Hello, could you assign this to me?

**Comment by Saloni6111** [comment]
> Hello, could you assign this to me?

@llabhill Sure, it's already assigned to you. Please go ahead!

**Comment by Rohan5809** [comment]
Yes the input string is valid .. plzz let me know the further procedure

**Comment by sharayuanuse** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by Shikhar8765** [comment]
HI @Saloni6111 pls assign me this issue

**Comment by Arhaan-P** [comment]
Could you please assign this to me?

**Comment by Saloni6111** [comment]
> HI @Saloni6111 pls assign me this issue

@Shikhar8765 assigned to you, please go ahead

**Comment by Saloni6111** [comment]
merged!
