### ISSUE TITLE
Find Kth Largest Element in an Array

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#4]
You will be given an unsorted array and you have to return the Kth largest element.

**Comment by Amber-Mishra-2003** [comment]
@Saloni6111  is this issue still open ?

**Comment by Saloni6111** [comment]
> @Saloni6111 is this issue still open ?

yes, I already assigned to you. If you want please go ahead!

**Comment by raxvab** [comment]
Hi @Saloni6111  Can you please assign it to me 
Here's my leetcode:-https://leetcode.com/u/whyybhav/
