### ISSUE TITLE
Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#40]
You are given an array where the i-th element is the price of a stock on day i. Find the maximum profit you can achieve from one transaction.

**Comment by Vishrut99** [comment]
i want to make Contribution in it...

**Comment by Saloni6111** [comment]
> i want to make Contribution in it...

Sure @Vishrut99 , Go ahead!

**Comment by Sameeratweb** [comment]
please give me a chance for contibutions
