### ISSUE TITLE
Move Zeroes

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#41]
Description: Write a function that moves all 0s in an array to the end while maintaining the relative order of the non-zero elements.
Constraints: Do this in-place without making a copy of the array.

Example:

Input: [0,1,0,3,12]
Output: [1,3,12,0,0]

**Comment by Brijeshthummar02** [comment]
hi @Saloni6111 assign me the task.

**Comment by Brijeshthummar02** [comment]
hi @Saloni6111 assign me the task.

**Comment by Saloni6111** [comment]
> hi @Saloni6111 assign me the task.

@Brijeshthummar02  it's already assigned to you. Please go ahead!

**Comment by Aditya-K477** [comment]
Please assign this issue to me

**Comment by dddhir** [comment]
hi @Saloni6111 please assign it to me

**Comment by Visha17** [comment]
Hi @Saloni6111 ,I am eager to solve this proble.could you please assign me this task?!
