### ISSUE TITLE
Fizz Buzz

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#42]
Description: Write a program that outputs numbers from 1 to n. But for multiples of three, output "Fizz" instead of the number, and for multiples of five, output "Buzz". For numbers which are multiples of both three and five, output "FizzBuzz".

Example:
Input: n = 15
Output: ["1", "2", "Fizz", "4", "Buzz", "Fizz", "7", "8", "Fizz", "Buzz", "11", "Fizz", "13", "14", "FizzBuzz"]

**Comment by Tanishka534** [comment]
Please Assign me this issue

**Comment by SalmanDeveloperz** [comment]
Hi @Saloni6111 
I'd love to work on this issue. Could you please assign it to me? I'll get started right away!

**Comment by Saloni6111** [comment]
> Please Assign me this issue

Sure @Tanishka534 , it's already assigned to you. Please go ahead!
