### ISSUE TITLE
Product of Array Except Self

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#43]
Description: Given an array nums of n integers, return an array output such that output[i] is equal to the product of all the elements of nums except nums[i].

Constraints: You must solve it without division and in O(n) time.

Example:
Input: [1,2,3,4]
Output: [24,12,8,6]

**Comment by Saloni6111** [comment]
> i want to do this problem...

@Vishrut99 Sure, it's already assigned to you. Please go ahead!

**Comment by Rajesh-1234567** [comment]
Hello!
Kindly please assign me this issue.
