### ISSUE TITLE
Subarray Sum Equals K

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#44]
Description: Given an array of integers nums and an integer k, find the total number of continuous subarrays whose sum equals k.

Example:
Input: nums = [1,1,1], k = 2
Output: 2 (subarrays: [1,1], [1,1])

**Comment by NukulKumawat** [comment]
Hey @Saloni6111 could you assign me this.

**Comment by Saloni6111** [comment]
> Hey @Saloni6111 could you assign me this.

Sure @NukulKumawat , it's already assigned to you. Please go ahead!
