### ISSUE TITLE
3Sum

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#46]
Description: Given an array nums of n integers, find all unique triplets that sum to zero.

Constraints: The solution should not return duplicate triplets.

Example:
Input: [-1, 0, 1, 2, -1, -4]
Output: [[-1, 0, 1], [-1, -1, 2]]

**Comment by rastogi30** [comment]
hello @Saloni6111 assign me the task.

**Comment by Saloni6111** [comment]
> hello @Saloni6111 assign me the task.

Sure @rastogi30 , it's already assigned to you. Please go ahead!

**Comment by Siddhaarth19** [comment]
@Saloni6111, please assign me this.

**Comment by Rajesh-1234567** [comment]
Hello!
Kindly please assign me this issue.
