### ISSUE TITLE
Set Matrix Zeroes

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#47]
Description: Given a m x n matrix, if an element is 0, set its entire row and column to 0. Do this in-place.

Constraints: Use constant space if possible.

Example:
Input: [[1,1,1],[1,0,1],[1,1,1]]
Output: [[1,0,1],[0,0,0],[1,0,1]]

**Comment by NinadShegokar** [comment]
Hello @Saloni6111, I would love to contribute to this problem! Could you please assign it to me?

**Comment by Saloni6111** [comment]
> Hello @Saloni6111, I would love to contribute to this problem! Could you please assign it to me?

Sure @NinadShegokar , it's already assigned to you. Please go ahead!
