### ISSUE TITLE
Rotting Oranges

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#48]
Description: You are given a grid where each cell is either empty (0), contains a fresh orange (1), or a rotten orange (2). Every minute, rotten oranges rot adjacent fresh oranges. Return the minimum number of minutes that must pass until no fresh orange remains. If it is impossible, return -1.

Example:
Input: [[2,1,1],[1,1,0],[0,1,1]]
Output: 4

**Comment by RudraJy** [comment]
Heyy @Saloni6111, could you assign me this issue? I'd like to work on it.

**Comment by Saloni6111** [comment]
> Heyy @Saloni6111, could you assign me this issue? I'd like to work on it.

Sure @RudraJy , it's already assigned to you. Please go ahead!
