### ISSUE TITLE
Palindromic Substrings

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#49]
Description: Given a string s, return the number of palindromic substrings in it. A substring is a palindrome if it reads the same backward as forward.

Example:
Input: "abc"
Output: 3 (substrings: "a", "b", "c")

**Comment by Vishrut99** [comment]
I want to make pull request so pls assign me

**Comment by Saloni6111** [comment]
> I want to make pull request so pls assign me

@Vishrut99 Go ahead!

**Comment by NimraAslamkhan** [comment]
assigned this to me
