### ISSUE TITLE
Minimum Window Substring

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#50]
Description: Given two strings s and t, return the minimum window in s which will contain all the characters in t.

Constraints: If no such window exists, return an empty string.

Example:
Input: s = "ADOBECODEBANC", t = "ABC"
Output: "BANC"

**Comment by rastogi30** [comment]
hello @Saloni6111 assign me the task.

**Comment by Saloni6111** [comment]
> hello @Saloni6111 assign me the task.

Sure @rastogi30 , it's already assigned to you. Please go ahead!

**Comment by Rajesh-1234567** [comment]
Hello!
Kindly please assign me this issue.
