### ISSUE TITLE
Word Search II

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#51]
Description: Given a board of characters and a list of words, find all words that exist on the board. A word can be constructed from letters of adjacent cells, where "adjacent" cells are those horizontally or vertically neighboring.

Example:
Input: board = [["o","a","a","n"],["e","t","a","e"],["i","h","k","r"],["i","f","l","v"]], words = ["oath","pea","eat","rain"]
Output: ["oath","eat"]

**Comment by sharayuanuse** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by Saloni6111** [comment]
> I want to work on this issue. Can you assign it to me?

Sure @sharayuanuse , it's already assigned to you. Please go ahead!
