### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#52]
Description: Write a program to solve a Sudoku puzzle by filling the empty cells. 
The empty cells are represented by the character '.'. You must solve the puzzle using backtracking.

Example:
Input: board = [["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."], ... ]
Output: The filled board where all empty spaces are replaced with valid numbers.

**Comment by mauryapradeep** [comment]
Hii @Saloni6111 please assign me this Problem!

**Comment by Saloni6111** [comment]
> Hii @Saloni6111 please assign me this Problem!

Sure, it's already assigned to you. Please go ahead!

**Comment by Rajesh-1234567** [comment]
Hello!
Kindly please assign me this issue.

**Comment by dauntless05** [comment]
hi can please assign it to me !!
thanks
