### ISSUE TITLE
Climbing Stairs

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#54]
Description: You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

Example:
Input: n = 3
Output: 3 (There are three ways: 1 step + 1 step + 1 step, 1 step + 2 steps, 2 steps + 1 step)

**Comment by Saloni6111** [comment]
> @Saloni6111, I kindly request that this issue be assigned to me and labeled under Hacktoberfest. I am excited to contribute and would love to take responsibility for it.

Yes @SreyaSudheeran , it's already assigned to you. Please go ahead!

**Comment by poswalsameer** [comment]
Hi @Saloni6111, can I start working on this problem?

**Comment by Saloni6111** [comment]
> Hi @Saloni6111, can I start working on this problem?

OK! please procced

**Comment by herambchaudhari4121** [comment]
Update README.md #1
I hope this message finds you well. I recently submitted a pull request (PR) to your project as part of Hacktoberfest, and I would be grateful if you could take a moment to review it.

If there are any changes or improvements needed, please feel free to let me know, and I would be happy to address them.

Thank you for maintaining such a great project, and I look forward to your feedback.
