### ISSUE TITLE
Add Two Numbers (linked lists)

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#55]
Description: You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.

Example:
Input: l1 = [2,4,3], l2 = [5,6,4]
Output: [7,0,8] (342 + 465 = 807)

**Comment by Tanishka534** [comment]
Please Assign me this issue , i can do it

**Comment by DevendraJaiswal074** [comment]
Hii @Saloni6111 
I'd love the opportunity to tackle this issue. Could you assign me to solve it, please?

**Comment by Saloni6111** [comment]
> Hii @Saloni6111 I'd love the opportunity to tackle this issue. Could you assign me to solve it, please?

Sure @DevendraJaiswal074 , it's already assigned to you. Please go ahead!

**Comment by Shikhar8765** [comment]
Hi @Saloni6111  pls assign me this issue.

**Comment by Rajesh-1234567** [comment]
Hello!
Kindly please assign me this issue.

**Comment by dauntless05** [comment]
hi can please assign it to me !!
thanks

**Comment by Utkarsh-Aggarwal** [comment]
hi i am a second year student , paving my way into open source can please assign this issue to me @Saloni6111
