### ISSUE TITLE
Group Anagrams

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#56]
Description: Given an array of strings, group the anagrams together. You can return the answer in any order.
Constraints: Each input string will only consist of lowercase letters.

Example:
Input: ["eat","tea","tan","ate","nat","bat"]
Output: [["bat"],["nat","tan"],["ate","eat","tea"]]

**Comment by NinadShegokar** [comment]
@Saloni6111 please assign this me

**Comment by Saloni6111** [comment]
> @Saloni6111 please assign this me

Sure @NinadShegokar , it's already assigned to you. Please go ahead!
