### ISSUE TITLE
Minimum Number of Refueling Stops

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#57]
Description: A car travels from a starting point to a destination which is target miles away. The car has an initial fuel of startFuel gallons. Along the way, there are gas stations, and you can stop at each station to refuel. Return the minimum number of refueling stops to reach the destination. If it is impossible to reach the destination, return -1.

Example:
Input: target = 100, startFuel = 10, stations = [[10,60],[20,30],[30,30],[60,40]]
Output: 2 (Refuel at station 0 and 3)

**Comment by sharayuanuse** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by Saloni6111** [comment]
> I want to work on this issue. Can you assign it to me?

Sure @sharayuanuse , it's already assigned to you. Please go ahead!

**Comment by Rajesh-1234567** [comment]
Hello!
Kindly please assign me this issue.

**Comment by Saloni6111** [comment]
@sharayuanuse Merged!
