### ISSUE TITLE
Maximum Depth of Binary Tree

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#58]
Description: Given the root of a binary tree, return its maximum depth.

Example:
Input: root = [3,9,20,null,null,15,7]
Output: 3

**Comment by Shikhar8765** [comment]
Hello,I think I am well suited for solving this problem.
I request you to assign me the issue.
Thank You

**Comment by Amber-Mishra-2003** [comment]
@Saloni6111 is this issue still open, can you please assign it to me?

**Comment by Saloni6111** [comment]
> Hello, @Saloni6111 I think I am well suited for solving this problem. I request you to assign me the issue. Thank You

@Shikhar8765 Go ahead

**Comment by hemanthhhhhh** [comment]
Kindly assign the issue
