### ISSUE TITLE
N-Queens

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#64]
Description: The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other. Return all distinct solutions to the n-queens puzzle.

Example:
Input: n = 4
Output: [[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]

**Comment by harshit1142** [comment]
@Saloni6111 can you assign me this issue?

**Comment by Saloni6111** [comment]
> @Saloni6111 can you assign me this issue?

Sure @harshit1142 , it's already assigned to you. Please go ahead!
