### ISSUE TITLE
Longest Increasing Path in a Matrix

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#65]
Description: Given an m x n matrix, return the length of the longest increasing path in the matrix. From each cell, you can move in four directions: left, right, up, or down. You may not move diagonally or move outside the boundary.

Example:
Input: matrix = [[9,9,4],[6,6,8],[2,1,1]]
Output: 4 (The longest increasing path is [1, 2, 6, 9])

**Comment by sharayuanuse** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by Saloni6111** [comment]
> I want to work on this issue. Can you assign it to me?

Sure @sharayuanuse , it's already assigned to you. Please go ahead!

**Comment by Amber-Mishra-2003** [comment]
@Saloni6111 is this issue still open? if yes, can you please assign it to me?
