### ISSUE TITLE
Merge k Sorted Lists

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#66]
Description: You are given an array of k linked lists, each linked list is sorted in ascending order. Merge all the linked lists into one sorted linked list and return it.

Example:
Input: lists = [[1,4,5],[1,3,4],[2,6]]
Output: [1,1,2,3,4,4,5,6]

**Comment by sharayuanuse** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by Anikesh02** [comment]
@Saloni6111 I want to solve this issue using C++. Can you please assign it to me?

**Comment by Saloni6111** [comment]
> I want to work on this issue. Can you assign it to me?

Hi @sharayuanuse , it's already assigned to you. Please go ahead!

**Comment by Saloni6111** [comment]
> @Saloni6111 I want to solve this issue using C++. Can you please assign it to me?

Sure @Anikesh02 , it's already assigned to you. Please go ahead!
