### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#67]
Description: Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

Example:
Input: height = [0,1,0,2,1,0,1,3,2,1,2,1]
Output: 6

**Comment by harshit1142** [comment]
Please assign me .

**Comment by Saloni6111** [comment]
> @Saloni6111 Can you assign me this issue ?

PR is already merged for this
