### ISSUE TITLE
Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by KamakshiOjha** [Saloni6111/DSA_Problems-Hacktoberfest-2024#68]
Description : Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.
The overall run time complexity should be O(log (m+n)).

Language : JAVA

PLEASE ASSIGN THIS ISSUE UNDER HACKTOBERFEST 2024

**Comment by Tanishka534** [comment]
Please Assign me this issue , i can do it

**Comment by Saloni6111** [comment]
> Please Assign me this issue , i can do it

Sure @Tanishka534 , it's already assigned to you. Please go ahead!

**Comment by KamakshiOjha** [comment]
Could you let me know why I wasn't assigned this issue, even though I was the one who initially opened it?

**Comment by Saloni6111** [comment]
> Could you let me know why I wasn't assigned this issue, even though I was the one who initially opened it?

@KamakshiOjha Sorry, but you haven't mentioned anywhere that you want to work on this issue you only said to keep hacktoberfest level.
