### ISSUE TITLE
 Palindrome Number

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#7]
Write a function where we are given an integer x, return true if x is a palindrome, and false otherwise.

Example :
```
Input: x = 121
Output: true
Explanation: 121 reads as 121 from left to right and from right to left.
```

**Comment by georgioupanayiotis** [comment]
@Saloni6111 can you please assign me this ticket ?

**Comment by Saloni6111** [comment]
@georgioupanayiotis Sure, Please go ahead

**Comment by georgioupanayiotis** [comment]
@Saloni6111 created the PR here https://github.com/Saloni6111/DSA_Problems-Hacktoberfest-2024/pull/53

**Comment by georgioupanayiotis** [comment]
@Saloni6111 merge it and add label `hacktoberfest-accepted`

**Comment by Saloni6111** [comment]
> @Saloni6111 merge it and add label `hacktoberfest-accepted`

@georgioupanayiotis will merge after 12:00AM once hacktoberfest starts or you want me to merge now?
