### ISSUE TITLE
Tower of Hanoi

### ISSUE THREAD

**Issue by pankaj-bind** [Saloni6111/DSA_Problems-Hacktoberfest-2024#77]
The Tower of Hanoi is a classic recursive algorithm used to solve a mathematical puzzle. It involves three rods and a set of disks of different sizes. The objective is to move all the disks from one rod to another, following these rules: only one disk can be moved at a time, a larger disk cannot be placed on top of a smaller one, and all disks must be moved from the source rod to the destination rod using an auxiliary rod.

**Comment by mdyousufniaz** [comment]
I would like to work on this problem, can u assign me on it ?

**Comment by Saloni6111** [comment]
> I would like to work on this problem, can u assign me on it ?

@mdyousufniaz Sure, it's already assigned to you. Please go ahead!

**Comment by Arhaan-P** [comment]
Could you please assign this to me

**Comment by Saloni6111** [comment]
merged!
