### ISSUE TITLE
Rabin-Karp Algorithm

### ISSUE THREAD

**Issue by pankaj-bind** [Saloni6111/DSA_Problems-Hacktoberfest-2024#80]
The Rabin-Karp Algorithm is a string-searching algorithm that uses hashing to find a pattern within a text. It works by calculating a hash value for the pattern and for each substring of the text with the same length as the pattern. If the hash values match, it checks the actual substring to confirm the match. This technique is efficient for multiple pattern searches or when dealing with large texts, as it reduces the number of string comparisons. 

Please assign me

**Comment by Saloni6111** [comment]
merged!
