### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_Problems-Hacktoberfest-2024#9]
write an algorithm for selection sort.

**Comment by raxvab** [comment]
Hi @Saloni6111  Can you please assign it to me 
Here's my leetcode:-https://leetcode.com/u/whyybhav/

**Comment by dauntless05** [comment]
hi please assign this to me!!

**Comment by Utkarsh-Aggarwal** [comment]
please assign this to  me my gfg profile https://www.geeksforgeeks.org/user/utkarshagbfsx/
