### ISSUE TITLE
Construct Binary Tree from Inorder and PostOrder Traversal

### ISSUE THREAD

**Issue by Tanishka534** [Saloni6111/DSA_Problems-Hacktoberfest-2024#96]
Problem Statement: Given the Postorder and Inorder traversal of a Binary Tree, construct the Unique Binary Tree represented by them.
Example :
Input: Inorder: [ 40, 20 , 50, 10, 60, 30], Postorder: [40, 50, 20, 60, 30, 10]
Output:
<img width="419" alt="image" src="https://github.com/user-attachments/assets/0d954bde-bd30-400c-bac7-f2f0bb99add2">

**Comment by Tanishka534** [comment]
Kindly Please Assign me this issue

**Comment by Saloni6111** [comment]
> Kindly Please Assign me this issue

@Tanishka534 Done

**Comment by Saloni6111** [comment]
merged!
